# Generated by Django 4.2.2 on 2023-07-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_rename_starting_bid_listing_current_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
