# Generated by Django 4.2.2 on 2023-07-25 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_listing_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
