# Generated by Django 4.2.2 on 2023-07-25 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_listing_image_url_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
