# Generated by Django 4.2.2 on 2023-07-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_listing_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="bid",
        ),
        migrations.AddField(
            model_name="bid",
            name="bid_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_listing",
                to="auctions.listing",
            ),
        ),
    ]
